name = "syugo-sin-worker"
main = "cloudflare/worker.js"
compatibility_date = "2025-08-15"

account_id = "22a595fc9b44d017afe09d00fc1157fa"

workers_dev = true

[dev]
port = 8787
local_protocol = "http"

[vars]
OPENAI_MODEL = "gpt-4o-mini"